import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import { getJobsDetail, JobsProps } from "../../services/jobs";

interface IJobProps {
    job: JobsProps;
}

const Job: React.FC<IJobProps> = ({ job }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>{"Create Next App"}</title>
                <meta name={"description"} content={"Generated by create next app"} />
                <link rel={"icon"} href={"/favicon.ico"} />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>{"Job Detail"}</h1>
                <div className={styles.grid}>
                    <h2>{job.title} &rarr;</h2>
                    <p>{job.category}</p>
                    <p>{job.description}</p>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href={"http://nextjs.com"}
                    target={"_blank"}
                    rel={"noopener noreferrer"}
                >
                    {"Powered By NextJS"}
                </a>
            </footer>
        </div>
    );
}

export async function getServerSideProps({ params }) {
    const id = params.id;
    const jobDetail = await getJobsDetail(id);
    return {
        props: { job: jobDetail }
    };
}


export default Job;