import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import { getJobsList, JobsProps } from "../services/jobs";
import { Card, CardBody, CardTitle, CardSubtitle, CardText } from "reactstrap";

interface IHomeProps {
  jobs: Array<JobsProps>;
}

const Home: React.FC<IHomeProps> = ({ jobs }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{"Create Next App"}</title>
        <meta name={"description"} content={"Generated by create next app"} />
        <link rel={"icon"} href={"/favicon.ico"} />
      </Head>

      <main>
        <h1 className={styles.title}>{"Job List"}</h1>
        <div className={styles.grid}>
          {jobs.map((job, index) => (
            <Link href={`/jobs/${job.id}`} key={index}>
              <Card style={{ width: '18rem' }} >
                <img alt="Sample" src="https://picsum.photos/300/200" />
                <CardBody>
                  <CardTitle tag="h5">{job.title}</CardTitle>
                  <CardSubtitle className="mb-2 text-muted" tag="h6">{job.category}
                  </CardSubtitle>
                  <CardText> {job.description}
                  </CardText>
                </CardBody>
              </Card>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href={"http://nextjs.com"}
          target={"_blank"}
          rel={"noopener noreferrer"}
        >
          {"Powered By NextJS"}
        </a>
      </footer>
    </div>
  );
};

export async function getServerSideProps() {
  const jobs = await getJobsList();
  return {
    props: { jobs },
  };
}

export default Home;
