import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import { getJobsList, JobsProps } from "../services/jobs";
import { Card } from "antd";

const { Meta } = Card;

interface IHomeProps {
  jobs: Array<JobsProps>;
}

const Home: React.FC<IHomeProps> = ({ jobs }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{"Create Next App"}</title>
        <meta name={"description"} content={"Generated by create next app"} />
        <link rel={"icon"} href={"/favicon.ico"} />
      </Head>

      <main>
        <h1 className={styles.title}>{"Job List"}</h1>
        <div className={styles.grid}>
          {jobs.map((job, index) => (
            <Link href={`/jobs/${job.id}`} key={index}>
              <Card
                hoverable
                style={{ width: 240 }}
                cover={
                  <img
                    alt={job.title}
                    src={
                      "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png"
                    }
                  />
                }
              >
                <Meta title={job.title} description={job.category} />
                <p>{job.description}</p>
              </Card>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href={"http://nextjs.com"}
          target={"_blank"}
          rel={"noopener noreferrer"}
        >
          {"Powered By NextJS"}
        </a>
      </footer>
    </div>
  );
};

export async function getServerSideProps() {
  const jobs = await getJobsList();
  return {
    props: { jobs },
  };
}

export default Home;
