import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import { getJobsList, JobsProps } from "../services/jobs";

interface IHomeProps {
  jobs: Array<JobsProps>;
}

const Home: React.FC<IHomeProps> = ({ jobs }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{"Create Next App"}</title>
        <meta name={"description"} content={"Generated by create next app"} />
        <link rel={"icon"} href={"/favicon.ico"} />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{"Job List"}</h1>
        <div className={styles.grid}>
          {jobs.map((job, index) => (
            <Link href={`/jobs/${job.id}`} key={index}>
              <a className={styles.card}>
                <h2>{job.title} &rarr;</h2>
                <p>{job.description}</p>
              </a>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href={"http://nextjs.com"}
          target={"_blank"}
          rel={"noopener noreferrer"}
        >
          {"Powered By NextJS"}
        </a>
      </footer>
    </div>
  );
};

export async function getServerSideProps() {
  const jobs = await getJobsList();
  return {
    props: { jobs },
  };
}

export default Home;
